CPPFLAGS=-std=c++17 -Wno-return-type -g

all:
	g++ src/Main.cpp \
	src/CanvasController.cpp \
	src/Animation.cpp \
	src/Canvas.cpp \
	src/Frame.cpp \
	src/KeyboardManager.cpp \
	src/Globals.cpp -g -o out -lallegro_primitives -lallegro_ttf -lallegro_font -lallegro -Wno-return-type
