all:
	g++ src/Main.cpp \
	src/GameClass.cpp \
	src/Menu.cpp \
	src/MenuButton.cpp \
	src/GameHost.cpp \
	src/Snake.cpp \
	src/Constants.cpp \
	src/Direction.cpp \
	-g -o game -lallegro_primitives -lallegro_ttf -lallegro_font -lallegro -Wno-return-type

test:
	./game